### ISSUE TITLE
New versions crash on startup

### ISSUE THREAD

**Issue by canton7** [RevoLand/Steam-Library-Manager#39]
Tried with v1.5.0.15 and v1.5.0.14. Crashes shortly after startup. Log contains:

```
2019-04-06 12:22:53.5792 FATAL System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at SharpRaven.RavenClient.Capture(SentryEvent event)
   at Steam_Library_Manager.Functions.FileSystem.GetDirectorySize(DirectoryInfo directoryPath, Boolean IncludeSubDirectories)
   at Steam_Library_Manager.Definitions.SteamLibrary.<>c.<UpdateJunks>b__34_1(DirectoryInfo x)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at Steam_Library_Manager.Definitions.SteamLibrary.UpdateJunks()
```

**Comment by RevoLand** [comment]
Should be a system or [Fody](https://github.com/Fody/Costura) related bug and shouldn't persist on the new version i will be sharing.

Will be releasing the new version rather than waiting to get French translation completed. Please let me know if the issue persists and thank you for the submission.
